from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('files/',views.files, name='files'),
    path('view_information/',views.view_information, name='view_information'),
    path('profile/',views.profile, name='profile'),
    path('logout_user/',views.logout_user, name='logout_user'),
    path('login_user/',views.login_user, name='login_user'),
    path('register/',views.register, name='register'),
    path('update/',views.update, name='update'),
    path('delete/',views.delete, name='delete'),
    path('profile_registration/',views.profile_registration, name='profile_registration'),
    path('zone_view/<arrange_order>',views.zone_view, name='zone_view'),
    path('zone_select/<zone_pick>',views.zone_select, name='zone_select'),
    path('zone_profile/<pk>',views.zone_profile, name='zone_profile'),
    path('todanames/<sequence>',views.todanames, name='todanames'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('dashone/',views.dashone, name='dashone'),
    path('dashone_sort/<pk>', views.dashone_sort, name='dashone_sort'),
    path('dashone_salary/<months>', views.dashone_salary, name='dashone_salary'),
    path('dashone_sortuser/<sortusers>', views.dashone_sortuser, name='dashone_sortuser'),
    path('dashone_settings/<radio_category>',views.dashone_settings, name='dashone_settings'),
    path('dashone_change_val/',views.dashone_change_val, name='dashone_change_val'),
    path('dashtwo/',views.dashtwo, name='dashtwo'),
    path('calendars/',views.calendars, name='calendars'),
    path('calendars_update/<date_pick>/<date_key>/',views.calendars_update, name='calendars_update'),
    path('attendance/',views.attendance, name='attendance'),
    path('attendance_update/<pk>/<monthyear>/',views.attendance_update, name='attendance_update'),
    path('notifications/',views.notifications, name='notifications'),
    path('overtime/',views.overtime, name='overtime'),
    path('overtime_select/<date_ot>/',views.overtime_select, name='overtime_select'),
    path('overtime_approval/', views.overtime_approval, name='overtime_approval'),
    path('overtime_approval_select/<month_day>/', views.overtime_approval_select, name='overtime_approval_select'),
    path('time_update/',views.time_update, name='time_update'),
    path('time_update_select/<month_day>', views.time_update_select, name='time_update_select'),

]