# Generated by Django 5.1.4 on 2025-02-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addinfo",
            name="driver_expired",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="addinfo",
            name="license_expired",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="addinfo",
            name="driver_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="addinfo",
            name="license_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="addinfo",
            name="seminar_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
