# Generated by Django 5.1.4 on 2025-02-21 04:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0003_remove_addinfo_driver_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addinfo",
            name="license_expired",
        ),
        migrations.RemoveField(
            model_name="addinfo",
            name="license_id",
        ),
    ]
