# Generated by Django 5.1.4 on 2025-02-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0004_remove_addinfo_license_expired_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="addinfo",
            name="seminar_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
