# Generated by Django 5.1.4 on 2025-02-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0005_addinfo_seminar_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addinfo",
            old_name="driver_expired",
            new_name="ID_expired",
        ),
        migrations.RenameField(
            model_name="addinfo",
            old_name="driver_issue",
            new_name="ID_issue",
        ),
        migrations.RenameField(
            model_name="addinfo",
            old_name="driver_id",
            new_name="ID_number",
        ),
        migrations.AlterField(
            model_name="addinfo",
            name="seminar_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
