# Generated by Django 5.1.4 on 2025-02-26 03:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0006_rename_driver_expired_addinfo_id_expired_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addinfo",
            name="seminar_date",
        ),
    ]
