# Generated by Django 5.1.4 on 2025-02-26 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0007_remove_addinfo_seminar_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seminars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seminar_date", models.DateField(blank=True, null=True)),
                (
                    "id_driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="information.addinfo",
                    ),
                ),
            ],
        ),
    ]
