# Generated by Django 5.1.4 on 2025-02-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0009_alter_seminars_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seminars",
            name="seminar_date",
        ),
        migrations.AddField(
            model_name="seminars",
            name="seminar_dates",
            field=models.DateField(blank=True, null=True),
        ),
    ]
