# Generated by Django 5.1.4 on 2025-03-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0012_alter_attendance_per_hour_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="per_hour",
        ),
        migrations.AddField(
            model_name="attendance",
            name="total_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="total_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
