# Generated by Django 5.1.4 on 2025-03-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "information",
            "0013_remove_attendance_per_hour_attendance_total_rate_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="log_in",
            field=models.DateTimeField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="log_out",
            field=models.TimeField(blank=True, max_length=30, null=True),
        ),
    ]
