# Generated by Django 5.1.4 on 2025-03-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "information",
            "0016_alter_aprs_2025_options_alter_febs_2025_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Augs_2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_attend", models.CharField(blank=True, max_length=30, null=True)),
                ("log_in", models.DateTimeField(blank=True, max_length=30, null=True)),
                ("log_out", models.TimeField(blank=True, max_length=30, null=True)),
                (
                    "total_hour",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
            ],
            options={
                "verbose_name_plural": "Augs_2025",
            },
        ),
        migrations.CreateModel(
            name="Decs_2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_attend", models.CharField(blank=True, max_length=30, null=True)),
                ("log_in", models.DateTimeField(blank=True, max_length=30, null=True)),
                ("log_out", models.TimeField(blank=True, max_length=30, null=True)),
                (
                    "total_hour",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
            ],
            options={
                "verbose_name_plural": "Decs_2025",
            },
        ),
        migrations.CreateModel(
            name="Jans_2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_attend", models.CharField(blank=True, max_length=30, null=True)),
                ("log_in", models.DateTimeField(blank=True, max_length=30, null=True)),
                ("log_out", models.TimeField(blank=True, max_length=30, null=True)),
                (
                    "total_hour",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
            ],
            options={
                "verbose_name_plural": "Jans_2025",
            },
        ),
        migrations.CreateModel(
            name="Julys_2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_attend", models.CharField(blank=True, max_length=30, null=True)),
                ("log_in", models.DateTimeField(blank=True, max_length=30, null=True)),
                ("log_out", models.TimeField(blank=True, max_length=30, null=True)),
                (
                    "total_hour",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
            ],
            options={
                "verbose_name_plural": "Julys_2025",
            },
        ),
        migrations.CreateModel(
            name="Junes_2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_attend", models.CharField(blank=True, max_length=30, null=True)),
                ("log_in", models.DateTimeField(blank=True, max_length=30, null=True)),
                ("log_out", models.TimeField(blank=True, max_length=30, null=True)),
                (
                    "total_hour",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
            ],
            options={
                "verbose_name_plural": "Junes_2025",
            },
        ),
        migrations.CreateModel(
            name="Mays_2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_attend", models.CharField(blank=True, max_length=30, null=True)),
                ("log_in", models.DateTimeField(blank=True, max_length=30, null=True)),
                ("log_out", models.TimeField(blank=True, max_length=30, null=True)),
                (
                    "total_hour",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
            ],
            options={
                "verbose_name_plural": "Mays_2025",
            },
        ),
        migrations.CreateModel(
            name="Novs_2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_attend", models.CharField(blank=True, max_length=30, null=True)),
                ("log_in", models.DateTimeField(blank=True, max_length=30, null=True)),
                ("log_out", models.TimeField(blank=True, max_length=30, null=True)),
                (
                    "total_hour",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
            ],
            options={
                "verbose_name_plural": "Novs_2025",
            },
        ),
        migrations.CreateModel(
            name="Octs_2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_attend", models.CharField(blank=True, max_length=30, null=True)),
                ("log_in", models.DateTimeField(blank=True, max_length=30, null=True)),
                ("log_out", models.TimeField(blank=True, max_length=30, null=True)),
                (
                    "total_hour",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
            ],
            options={
                "verbose_name_plural": "Octs_2025",
            },
        ),
        migrations.CreateModel(
            name="Septs_2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_attend", models.CharField(blank=True, max_length=30, null=True)),
                ("log_in", models.DateTimeField(blank=True, max_length=30, null=True)),
                ("log_out", models.TimeField(blank=True, max_length=30, null=True)),
                (
                    "total_hour",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
            ],
            options={
                "verbose_name_plural": "Septs_2025",
            },
        ),
    ]
