# Generated by Django 5.1.4 on 2025-03-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "information",
            "0018_aprs_2025_ot_approved_aprs_2025_ot_approved_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="aprs_2025",
            name="ot_approved_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="aprs_2025",
            name="ot_request_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="ot_approved_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="ot_request_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="augs_2025",
            name="ot_approved_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="augs_2025",
            name="ot_request_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="decs_2025",
            name="ot_approved_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="decs_2025",
            name="ot_request_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="febs_2025",
            name="ot_approved_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="febs_2025",
            name="ot_request_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="jans_2025",
            name="ot_approved_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="jans_2025",
            name="ot_request_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="julys_2025",
            name="ot_approved_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="julys_2025",
            name="ot_request_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="junes_2025",
            name="ot_approved_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="junes_2025",
            name="ot_request_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="mays_2025",
            name="ot_approved_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="mays_2025",
            name="ot_request_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="novs_2025",
            name="ot_approved_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="novs_2025",
            name="ot_request_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="octs_2025",
            name="ot_approved_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="octs_2025",
            name="ot_request_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="septs_2025",
            name="ot_approved_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="septs_2025",
            name="ot_request_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
