# Generated by Django 5.1.4 on 2025-04-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0020_alter_attendance_ot_approved_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="ot_approved_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
