# Generated by Django 5.1.4 on 2025-04-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0022_alter_aprs_2025_total_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jans_2025",
            name="total_hour",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="jans_2025",
            name="total_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="jans_2025",
            name="total_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
    ]
