# Generated by Django 5.1.4 on 2025-02-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0002_toda_zone_remove_profile_zonename_profile_toda_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/pictures/"
            ),
        ),
    ]
