# Generated by Django 5.1.4 on 2025-02-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0003_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todalist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_list", models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name="toda",
            old_name="name",
            new_name="name_toda",
        ),
        migrations.RenameField(
            model_name="zone",
            old_name="name",
            new_name="name_zone",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.AddField(
            model_name="zone",
            name="toda_name",
            field=models.ManyToManyField(blank=True, to="record.todalist"),
        ),
    ]
