# Generated by Django 5.1.4 on 2025-02-08 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0004_todalist_rename_name_toda_name_toda_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="toda",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="record.todalist",
            ),
        ),
        migrations.DeleteModel(
            name="Toda",
        ),
    ]
