# Generated by Django 5.1.4 on 2025-02-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0007_alter_bodynumber_name_body_alter_todalist_name_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bodynum",
        ),
        migrations.AlterField(
            model_name="todalist",
            name="name_list",
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name="Bodynumber",
        ),
    ]
