# Generated by Django 5.1.4 on 2025-02-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0010_profile_bodynum_alter_todalist_name_list_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/pictures/"
                    ),
                ),
            ],
        ),
    ]
