# Generated by Django 5.1.4 on 2025-02-11 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0020_todaname_profile_toda"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="toda",
            new_name="todaname",
        ),
    ]
