# Generated by Django 5.1.4 on 2025-02-11 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0025_rename_zone_name_todaname_toda_zone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="record.zone",
            ),
        ),
    ]
