# Generated by Django 5.1.4 on 2025-02-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0026_alter_profile_zone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="todaname",
        ),
        migrations.AddField(
            model_name="profile",
            name="nametoda",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
