# Generated by Django 5.1.4 on 2025-02-11 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0027_remove_profile_todaname_profile_nametoda"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="zone",
        ),
    ]
