# Generated by Django 5.1.4 on 2025-02-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0030_prorecord"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prorecord",
            old_name="license_id",
            new_name="driver_ID",
        ),
        migrations.RenameField(
            model_name="prorecord",
            old_name="seminar_date",
            new_name="license_ID",
        ),
        migrations.RenameField(
            model_name="prorecord",
            old_name="user_name",
            new_name="user_Name",
        ),
        migrations.RemoveField(
            model_name="prorecord",
            name="driver_id",
        ),
        migrations.AddField(
            model_name="prorecord",
            name="driver_Date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prorecord",
            name="license_Date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prorecord",
            name="seminar_Date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
