# Generated by Django 5.1.4 on 2025-02-16 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0033_remove_prorecord_driver_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prorecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("licenseid", models.CharField(blank=True, max_length=30, null=True)),
                ("driverid", models.CharField(blank=True, max_length=30, null=True)),
                ("seminar_date", models.DateTimeField(blank=True, null=True)),
                ("license_date", models.DateTimeField(blank=True, null=True)),
                ("driver_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user_Name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Prorecord",
        ),
    ]
