# Generated by Django 5.1.4 on 2025-02-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0036_rename_driver_date_recordpro_driver_dated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordpro",
            name="driver_dated",
            field=models.DateTimeField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="recordpro",
            name="license_dated",
            field=models.DateTimeField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="recordpro",
            name="seminar_dated",
            field=models.DateTimeField(blank=True, max_length=30, null=True),
        ),
    ]
