# Generated by Django 5.1.4 on 2025-02-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0045_delete_addinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="license_expired",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="license_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
