# Generated by Django 5.1.4 on 2025-02-04 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="date_shipped",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipped",
        ),
    ]
