# Generated by Django 5.1.4 on 2025-02-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_remove_order_date_shipped_remove_order_shipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped",
            field=models.BooleanField(default=False),
        ),
    ]
