# Generated by Django 5.1.4 on 2025-02-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_order_shipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_shipped",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
