# Generated by Django 5.1.4 on 2025-02-08 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Toda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="zonename",
        ),
        migrations.AddField(
            model_name="profile",
            name="toda",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="record.toda"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="zone",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="record.zone"
            ),
        ),
        migrations.DeleteModel(
            name="Zonename",
        ),
    ]
