# Generated by Django 5.1.4 on 2025-02-08 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0005_alter_profile_toda_delete_toda"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bodynumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_body", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="bodynum",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="record.bodynumber",
            ),
        ),
    ]
