# Generated by Django 5.1.4 on 2025-02-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0006_bodynumber_profile_bodynum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodynumber",
            name="name_body",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="todalist",
            name="name_list",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
