# Generated by Django 5.1.4 on 2025-02-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0008_remove_profile_bodynum_alter_todalist_name_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todalist",
            name="name_list",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
