# Generated by Django 5.1.4 on 2025-02-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0009_alter_todalist_name_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bodynum",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="todalist",
            name="name_list",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="zone",
            name="toda_name",
            field=models.ManyToManyField(to="record.todalist"),
        ),
    ]
