# Generated by Django 5.1.4 on 2025-02-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0017_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="toda",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="toda_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(upload_to="uploads/pictures/"),
        ),
        migrations.DeleteModel(
            name="Todalist",
        ),
    ]
