# Generated by Django 5.1.4 on 2025-02-11 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0019_profile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todaname",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_toda", models.CharField(max_length=50)),
                ("brgy_name", models.CharField(max_length=50)),
                (
                    "zone",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="record.zone",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="toda",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="record.todaname",
            ),
        ),
    ]
