# Generated by Django 5.1.4 on 2025-02-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0021_rename_toda_profile_todaname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todaname",
            old_name="zone",
            new_name="zone_toda",
        ),
        migrations.AlterField(
            model_name="todaname",
            name="brgy_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="todaname",
            name="name_toda",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
