# Generated by Django 5.1.4 on 2025-02-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0022_rename_zone_todaname_zone_toda_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todaname",
            name="zone_toda",
        ),
        migrations.AddField(
            model_name="todaname",
            name="zone_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="todaname",
            name="brgy_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
