# Generated by Django 5.1.4 on 2025-02-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0024_alter_profile_todaname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todaname",
            old_name="zone_name",
            new_name="toda_zone",
        ),
        migrations.AlterField(
            model_name="profile",
            name="todaname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
