# Generated by Django 5.1.4 on 2025-02-11 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0028_remove_profile_zone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="nametoda",
        ),
        migrations.RemoveField(
            model_name="todaname",
            name="toda_zone",
        ),
        migrations.AddField(
            model_name="profile",
            name="todaname",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="record.todaname",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="zone",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="record.zone"
            ),
        ),
        migrations.AddField(
            model_name="todaname",
            name="todazone",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="record.zone"
            ),
        ),
    ]
