# Generated by Django 5.1.4 on 2025-02-16 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0031_rename_license_id_prorecord_driver_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prorecord",
            old_name="driver_Date",
            new_name="driver_date",
        ),
        migrations.RenameField(
            model_name="prorecord",
            old_name="driver_ID",
            new_name="driver_id",
        ),
        migrations.RenameField(
            model_name="prorecord",
            old_name="license_Date",
            new_name="license_date",
        ),
        migrations.RenameField(
            model_name="prorecord",
            old_name="license_ID",
            new_name="license_id",
        ),
        migrations.RenameField(
            model_name="prorecord",
            old_name="seminar_Date",
            new_name="seminar_date",
        ),
    ]
