# Generated by Django 5.1.4 on 2025-02-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0032_rename_driver_date_prorecord_driver_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prorecord",
            name="driver_id",
        ),
        migrations.RemoveField(
            model_name="prorecord",
            name="license_id",
        ),
        migrations.AddField(
            model_name="prorecord",
            name="driverid",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="prorecord",
            name="licenseid",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
