# Generated by Django 5.1.4 on 2025-02-16 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0035_recordpro_delete_prorecords"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recordpro",
            old_name="driver_date",
            new_name="driver_dated",
        ),
        migrations.RenameField(
            model_name="recordpro",
            old_name="license_date",
            new_name="license_dated",
        ),
        migrations.RenameField(
            model_name="recordpro",
            old_name="seminar_date",
            new_name="seminar_dated",
        ),
    ]
