# Generated by Django 5.1.4 on 2025-02-16 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0037_alter_recordpro_driver_dated_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IDrecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idlicense", models.CharField(max_length=30)),
                ("idriver", models.CharField(max_length=30)),
                (
                    "seminar_dated",
                    models.DateTimeField(blank=True, max_length=30, null=True),
                ),
                (
                    "license_dated",
                    models.DateTimeField(blank=True, max_length=30, null=True),
                ),
                (
                    "driver_dated",
                    models.DateTimeField(blank=True, max_length=30, null=True),
                ),
                (
                    "user_Name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Recordpro",
        ),
    ]
