# Generated by Django 5.1.4 on 2025-02-16 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0038_idrecord_delete_recordpro"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IDrecord",
        ),
    ]
