# Generated by Django 5.1.4 on 2025-02-16 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0039_delete_idrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prorecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_id", models.CharField(max_length=20)),
                ("driver_id", models.CharField(max_length=20)),
                ("license_date", models.DateTimeField(max_length=20)),
                ("driver_date", models.DateTimeField(max_length=20)),
                ("seminar_date", models.DateTimeField(max_length=20)),
                (
                    "pro_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
