# Generated by Django 5.1.4 on 2025-02-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0041_addinfo_delete_prorecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addinfo",
            name="driver_date",
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="addinfo",
            name="driver_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="addinfo",
            name="license_date",
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="addinfo",
            name="license_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="addinfo",
            name="seminar_date",
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
    ]
