# Generated by Django 5.1.4 on 2025-02-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0042_alter_addinfo_driver_date_alter_addinfo_driver_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addinfo",
            name="pro_user",
        ),
        migrations.AddField(
            model_name="addinfo",
            name="user_addinfo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
