# Generated by Django 5.1.4 on 2025-02-16 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0044_alter_addinfo_user_addinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Addinfo",
        ),
    ]
