# Generated by Django 5.1.4 on 2025-04-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0047_notifies"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notifies",
            options={"verbose_name_plural": "Notifies"},
        ),
        migrations.AlterField(
            model_name="notifies",
            name="notify_user",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
