# Generated by Django 5.1.4 on 2025-02-16 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Addinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_id", models.CharField(blank=True, max_length=20, null=True)),
                ("driver_id", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "license_date",
                    models.DateTimeField(blank=True, max_length=20, null=True),
                ),
                (
                    "driver_date",
                    models.DateTimeField(blank=True, max_length=20, null=True),
                ),
                (
                    "seminar_date",
                    models.DateTimeField(blank=True, max_length=20, null=True),
                ),
                (
                    "user_addinfo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
