# Generated by Django 5.1.4 on 2025-02-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0002_addinfo_driver_expired_addinfo_license_expired_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addinfo",
            name="driver_date",
        ),
        migrations.RemoveField(
            model_name="addinfo",
            name="license_date",
        ),
        migrations.RemoveField(
            model_name="addinfo",
            name="seminar_date",
        ),
        migrations.AddField(
            model_name="addinfo",
            name="driver_issue",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="addinfo",
            name="driver_expired",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="addinfo",
            name="license_expired",
            field=models.DateField(blank=True, null=True),
        ),
    ]
