# Generated by Django 5.1.4 on 2025-02-26 04:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0008_seminars"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seminars",
            options={"verbose_name_plural": "Seminars"},
        ),
    ]
