# Generated by Django 5.1.4 on 2025-03-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0010_remove_seminars_seminar_date_seminars_seminar_dates"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_attend", models.CharField(blank=True, max_length=30, null=True)),
                ("log_in", models.DateTimeField(blank=True, max_length=20, null=True)),
                ("log_out", models.DateField(blank=True, null=True)),
                ("per_hour", models.DecimalField(decimal_places=2, max_digits=7)),
                ("total_hour", models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
