# Generated by Django 5.1.4 on 2025-03-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0011_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="per_hour",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="total_hour",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
