# Generated by Django 5.1.4 on 2025-03-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0014_alter_attendance_log_in_alter_attendance_log_out"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aprs_2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_attend_apr",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "log_in_apr",
                    models.DateTimeField(blank=True, max_length=30, null=True),
                ),
                ("log_out_apr", models.TimeField(blank=True, max_length=30, null=True)),
                (
                    "total_hour_apr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_rate_apr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_salary_apr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Febs_2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_attend_feb",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "log_in_feb",
                    models.DateTimeField(blank=True, max_length=30, null=True),
                ),
                ("log_out_feb", models.TimeField(blank=True, max_length=30, null=True)),
                (
                    "total_hour_feb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_rate_feb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_salary_feb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="attendance",
            name="total_hour",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="total_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="total_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
