# Generated by Django 5.1.4 on 2025-03-08 06:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "information",
            "0015_aprs_2025_febs_2025_alter_attendance_total_hour_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aprs_2025",
            options={"verbose_name_plural": "Aprs_2025"},
        ),
        migrations.AlterModelOptions(
            name="febs_2025",
            options={"verbose_name_plural": "Febs_2025"},
        ),
        migrations.RenameField(
            model_name="aprs_2025",
            old_name="log_in_apr",
            new_name="log_in",
        ),
        migrations.RenameField(
            model_name="aprs_2025",
            old_name="log_out_apr",
            new_name="log_out",
        ),
        migrations.RenameField(
            model_name="aprs_2025",
            old_name="total_hour_apr",
            new_name="total_hour",
        ),
        migrations.RenameField(
            model_name="aprs_2025",
            old_name="total_rate_apr",
            new_name="total_rate",
        ),
        migrations.RenameField(
            model_name="aprs_2025",
            old_name="total_salary_apr",
            new_name="total_salary",
        ),
        migrations.RenameField(
            model_name="aprs_2025",
            old_name="user_attend_apr",
            new_name="user_attend",
        ),
        migrations.RenameField(
            model_name="febs_2025",
            old_name="log_in_feb",
            new_name="log_in",
        ),
        migrations.RenameField(
            model_name="febs_2025",
            old_name="log_out_feb",
            new_name="log_out",
        ),
        migrations.RenameField(
            model_name="febs_2025",
            old_name="total_hour_feb",
            new_name="total_hour",
        ),
        migrations.RenameField(
            model_name="febs_2025",
            old_name="total_rate_feb",
            new_name="total_rate",
        ),
        migrations.RenameField(
            model_name="febs_2025",
            old_name="total_salary_feb",
            new_name="total_salary",
        ),
        migrations.RenameField(
            model_name="febs_2025",
            old_name="user_attend_feb",
            new_name="user_attend",
        ),
    ]
