# Generated by Django 5.1.4 on 2025-04-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0021_alter_attendance_ot_approved_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aprs_2025",
            name="total_hour",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
    ]
