# Generated by Django 5.1.4 on 2025-04-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0023_alter_jans_2025_total_hour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jans_2025",
            name="total_hour",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="jans_2025",
            name="total_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="jans_2025",
            name="total_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
