# Generated by Django 5.1.4 on 2025-04-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0024_alter_jans_2025_total_hour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jans_2025",
            name="decoy_vars",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
